### ISSUE TITLE
Solve Critical vulnerabilities

### ISSUE THREAD

**Issue by ashishhk** [commercetools/sphere-stock-import#111]
https://github.com/commercetools/sphere-stock-import/security/dependabot

**Comment by VineetKumarKushwaha** [comment]
https://github.com/commercetools/sphere-stock-import/commit/f3aaad317c7a1d837a473c4f856fdf0e2fb36606 This commit has removed all the critical vulnerabilities however there is one high and moderate which would require good amount of refactoring because bump package to their next major version won't work in that case.

**Comment by lojzatran** [comment]
Hi @VineetKumarKushwaha thank you for the fix. It is enough for now. Please let me know once it is released.

**Comment by VineetKumarKushwaha** [comment]
sphere-stock-import@3.0.6 released new version. Closing the issue please re-open if anything else needed

**Comment by lojzatran** [comment]
Hi @VineetKumarKushwaha it seems like the critical vulnerability is still there in the old version of lodash: https://github.com/commercetools/sphere-stock-import/blob/0c651f48dd0718b87ca279dae5baf0068a58c9d7/package-lock.json#L2344

**Comment by lojzatran** [comment]
Hi @VineetKumarKushwaha thank you for the release, but it does not work properly. I tested it and your fix works only if you run `npm i` in this project. 

I have this project as an dependency in another project. When I run `npm i` in the main project, `sphere-stock-import` installs again the old lodash dependency with critical vulnerability.

**Comment by lojzatran** [comment]
Seems like I cannot reopen this issue, so I opened a new issue.

**Comment by VineetKumarKushwaha** [comment]
@lojzatran I closed the newly created issue and let's use this ticket for the discussion. Yes unfortunately to make a fix for all consumed package we have to bump the version which is quite not feasible at the moment and will take some time. To mitigate this issue I would suggest to use the same approach to lock the lodash and other dependencies which are transitive. [Here is the package](https://www.npmjs.com/package/npm-force-resolutions) you can use to lock the transitive dependencies.

**Comment by lojzatran** [comment]
@VineetKumarKushwaha thank you for your suggestion, I will do it then. But does it mean that this project is not supported anymore? Otherwise it doesn't look good to have old dependencies and build failing.

**Comment by VineetKumarKushwaha** [comment]
@lojzatran there is no active development on this and its on the path of depreciation
