### ISSUE TITLE
Critical vulnerability when running the project as a dependency

### ISSUE THREAD

**Issue by lojzatran** [commercetools/sphere-stock-import#112]
There is a critical vulnerability in lodash for this project. Fix was done [here](https://github.com/commercetools/sphere-stock-import/issues/111) but it did not work correctly and still installs vulnerable dependency. 

I tested it and your fix works only if you run npm i in this project. I have this project as an dependency in another project. When I run npm i in the main project, sphere-stock-import installs again the old lodash dependency with critical vulnerability.

**Comment by VineetKumarKushwaha** [comment]
Duplicate of https://github.com/commercetools/sphere-stock-import/issues/111
